/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/minimalistic_modern_office.glb --transform --shadows --instance
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minimalistic-modern-office-5540183da1c7452f810f8de33734879a
Title: Minimalistic Modern Office
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
	const { nodes, materials } = useGLTF(
		"/minimalistic_modern_office-transformed.glb",
	);
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.35}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group
						rotation={[-Math.PI / 2, Math.PI / 2, 0]}
						scale={[410, 1230, 410]}
					>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Glass_0
									.geometry
							}
							material={materials.Glass}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Structure_0
									.geometry
							}
							material={materials.Structure}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Background_0
									.geometry
							}
							material={materials.Background}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Table_0
									.geometry
							}
							material={materials.Table}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Chair_0
									.geometry
							}
							material={materials.Chair}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Plants_0
									.geometry
							}
							material={materials.Plants}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Plants_0_1
									.geometry
							}
							material={materials.Plants}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_Lights_0
									.geometry
							}
							material={materials.Lights}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={
								nodes.Minimalistic_Modern_Office_LightEmission_0
									.geometry
							}
							material={materials.LightEmission}
						/>
						<mesh
							castShadow
							receiveShadow
							geometry={nodes.Carpet_Carpet_0.geometry}
							material={materials.Carpet}
							position={[1, 0, 2.44]}
							rotation={[0, -Math.PI / 2, 0]}
							scale={[1.39, 0.46, 1.39]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/minimalistic_modern_office-transformed.glb");
