/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/saturn.glb --transform
Author: SunnyChen753/SW fan (https://sketchfab.com/sunnychen753)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/saturn-7f4800dd923d420fa63a905ff5cad423
Title: Saturn
*/

import React, { useRef } from "react";
import { Float, MeshTransmissionMaterial, useGLTF } from "@react-three/drei";
import { useMemo } from "react";

export function Model(props) {
	const { nodes, materials } = useGLTF("/saturn-transformed.glb");
	const material = useMemo(() => {
		return (
			<MeshTransmissionMaterial
				backside
				backsideResolution={128}
				backsideThickness={6}
				envMapIntensity={0.4}
				roughness={0.2}
				samples={2}
				distortion={3}
				temporalDistortion={0.1}
				iridescence={0.25}
				ior={0.9}
			/>
		);
	}, []);

	return (
		<Float>
			{" "}
			<group {...props} dispose={null}>
				<group position={[20.91, 12.54, 0.12]} scale={2}>
					<mesh scale={125}>
						<sphereGeometry />
						{material}
					</mesh>
					<group
						position={[-15.11, 1.6, 0.35]}
						rotation={[Math.PI, -0.87, Math.PI]}
					>
						<mesh geometry={nodes.Ring_Mat1_0.geometry}>
							{material}
						</mesh>
						<mesh geometry={nodes.Ring_Mat1_0_1.geometry}>
							{material}
						</mesh>
					</group>
				</group>
			</group>
		</Float>
	);
}

useGLTF.preload("/saturn-transformed.glb");
